name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.jsa
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependências
        run: npm install
        
      - name: Executar testes
        run: npm run test-controller

      - name: Subir a API
        run: npm start & 
      
      - name: Esperar a API estar funcionando
        run: sleep 5

      - name: Rodar os testes de API via HTTP
        run: npm run test-controller